### ISSUE TITLE
Publish with GitHub pages

### ISSUE THREAD

**Issue by ghost** [fuzzball-muck/muckman#2]
This is optional, but the repository itself can be viewed in browsers, live.
https://help.github.com/en/articles/configuring-a-publishing-source-for-github-pages
If you set it to just "master branch"

**Comment by wyld-sw** [comment]
Done!

**Comment by ghost** [comment]
https://fuzzball-muck.github.io/muckman/
It works!  I found the URL by using the default scheme, which is fine.
